# ---------------------------------------------------------------------------------------------------------------------
# REQUIRED PARAMETERS
# You must provide a value for each of these parameters.
# ---------------------------------------------------------------------------------------------------------------------

variable "lambda_function_arn" {
  description = "The Amazon Resource Name (ARN) identifying the Lambda Function trigger by CloudWatch"
}

# ---------------------------------------------------------------------------------------------------------------------
# OPTIONAL PARAMETERS
# These parameters have reasonable defaults.
# ---------------------------------------------------------------------------------------------------------------------

variable "description" {
  default     = ""
  description = "The description of the rule. "
}

variable "enable" {
  default     = false
  description = "Conditionally enables this module (and all it's ressources)."
}

variable "event_pattern" {
  default     = ""
  description = "(Required, if schedule_expression isn't specified) Event pattern described a JSON object."
}

variable "is_enabled" {
  default     = true
  description = "Whether the rule should be enabled (defaults to true)."
}

variable "name" {
  default     = ""
  description = "The rule's name. By default generated by Terraform."
}

variable "name_prefix" {
  default     = ""
  description = "The rule's name. Conflicts with name."
}

variable "schedule_expression" {
  default     = ""
  description = "(Required, if event_pattern isn't specified) Scheduling expression for triggering the Lambda Function using CloudWatch events. For example, cron(0 20 * * ? *) or rate(5 minutes)."
}

